name: Generate Platform Files

on: 
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate platform-specific files
        run: |
          cp DodgingTraffic.py "Linux Version"
          { echo "#!/usr/bin/env python3"; echo "##make while loop!!"; cat DodgingTraffic.py; } > temp && mv temp "Linux Version"

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "Linux Version"
          git commit -m "Auto-generate platform-specific files" || echo "No changes to commit"

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Push changes
        run: git push
